### ISSUE TITLE
trait bound `syn::ExprClosure: attribute_derive::parsing::AttributeBase` is not satisfied

### ISSUE THREAD

**Issue by ecton** [ModProg/attribute-derive#19]
When upgrading `refuse-macros` from 0.8 to 0.9, my usage of `syn::ExprClosure` no longer compiles with this error:

```rust
error[E0277]: the trait bound `syn::ExprClosure: attribute_derive::parsing::AttributeBase` is not satisfied
   --> refuse-macros/src/lib.rs:202:10
    |
202 | #[derive(FromAttr)]
    |          ^^^^^^^^ the trait `attribute_derive::parsing::AttributeBase` is not implemented for `syn::ExprClosure`
    |
    = help: the following other types implement trait `attribute_derive::parsing::AttributeBase`:
              bool
              char
              isize
              i8
              i16
              i32
              i64
              i128
            and 173 others
    = note: required for `std::option::Option<syn::ExprClosure>` to implement `attribute_derive::parsing::AttributeBase`
    = note: this error originates in the derive macro `FromAttr` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I'm not sure if this isn't meant to be supported, if there's a better syn type to be using, or if this is just an oversight.

Edit: Oops, didn't realize that I haven't pushed the macro changes yet. Here's what the usage looks like:

```rust
#[derive(FromAttr)]
#[attribute(ident = collectable)]
struct MapAsAttr {
    target: Option<syn::Type>,
    map: Option<syn::ExprClosure>,
}
```

**Comment by ModProg** [comment]
that is probably an oversight, why are you not using `Expr`? do you need to get the contents of the closure? if not `Expr` would have the advantage of also supporting e.g. paths.

**Comment by ModProg** [comment]
Did you enable `syn-full`? Some expressions are only supported with that enabled.

**Comment by ecton** [comment]
After our discussion on Discord, I've confirmed that `syn-full` does make it compile. This does mean it was a breaking change between 0.8 and 0.9. However, using `Expr` was also a much better suggestion anyways.
